### ISSUE TITLE
Ungracious errors uploading unsupported document types

### ISSUE THREAD

**Issue by ScorcherChar** [crocodoc/java-box-view#2]
When uploading an unsupported document type a strange an uninformative error is thrown from the guts of the SDK. Ideally there should be some validation and a more helpful error message.

See below when pointing your example 3 at a .jpg image;

Exception in thread "main" java.lang.UnsupportedOperationException: Multipart form entity does not implement #getContent()
	at org.apache.http.entity.mime.MultipartFormEntity.getContent(MultipartFormEntity.java:101)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:215)
	at org.apache.http.util.EntityUtils.toString(EntityUtils.java:291)
	at com.box.view.Request.error(Request.java:186)
	at com.box.view.Request.handleRequestError(Request.java:552)
	at com.box.view.Request.execute(Request.java:339)
	at com.box.view.Request.requestJson(Request.java:148)
	at com.box.view.Base.requestJson(Base.java:144)
	at com.box.view.Document.upload(Document.java:585)
	at com.box.view.Document.upload(Document.java:457)
	at com.box.view.BoxViewClient.upload(BoxViewClient.java:155)
	at Examples.example3(Examples.java:137)
	at Examples.main(Examples.java:39)

**Comment by bgoldman** [comment]
This is now fixed.
